/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AramaRouteImport } from './routes/arama'
import { Route as BilgiMerkeziRouteImport } from './routes/bilgi-merkezi'
import { Route as CerezPolitikasiRouteImport } from './routes/cerez-politikasi'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as GizlilikPolitikasiRouteImport } from './routes/gizlilik-politikasi'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as IadeVeIptalPolitikasiRouteImport } from './routes/iade-ve-iptal-politikasi'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as KaliteVeGuvenlikRouteImport } from './routes/kalite-ve-guvenlik'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as MesafeliSatisSozlesmesiRouteImport } from './routes/mesafeli-satis-sozlesmesi'
import { Route as OdemeRouteImport } from './routes/odeme'
import { Route as OnBilgilendirmeFormuRouteImport } from './routes/on-bilgilendirme-formu'
import { Route as SepetRouteImport } from './routes/sepet'
import { Route as SikcaSorulanSorularRouteImport } from './routes/sikca-sorulan-sorular'
import { Route as SiparisTakipRouteImport } from './routes/siparis-takip'
import { Route as TeslimatPolitikasiRouteImport } from './routes/teslimat-politikasi'
import { Route as TicariElektronikIletiOnayiRouteImport } from './routes/ticari-elektronik-ileti-onayi'
import { Route as UyelikSozlesmesiRouteImport } from './routes/uyelik-sozlesmesi'
import { Route as AuthenticatedHesabimRouteImport } from './routes/_authenticated/hesabim'
import { Route as AuthenticatedYonetimRouteImport } from './routes/_authenticated/yonetim'
import { Route as UrunlerIndexRouteImport } from './routes/urunler.index'
import { Route as UrunlerSlugRouteImport } from './routes/urunler.$slug'
import { Route as AuthenticatedSiparislerimIndexRouteImport } from './routes/_authenticated/siparislerim.index'
import { Route as AuthenticatedSiparislerimOrderNumberRouteImport } from './routes/_authenticated/siparislerim.$orderNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AramaRoute = AramaRouteImport.update({
  id: '/arama',
  path: '/arama',
  getParentRoute: () => rootRouteImport,
} as any)
const BilgiMerkeziRoute = BilgiMerkeziRouteImport.update({
  id: '/bilgi-merkezi',
  path: '/bilgi-merkezi',
  getParentRoute: () => rootRouteImport,
} as any)
const CerezPolitikasiRoute = CerezPolitikasiRouteImport.update({
  id: '/cerez-politikasi',
  path: '/cerez-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikPolitikasiRoute = GizlilikPolitikasiRouteImport.update({
  id: '/gizlilik-politikasi',
  path: '/gizlilik-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const IadeVeIptalPolitikasiRoute = IadeVeIptalPolitikasiRouteImport.update({
  id: '/iade-ve-iptal-politikasi',
  path: '/iade-ve-iptal-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const KaliteVeGuvenlikRoute = KaliteVeGuvenlikRouteImport.update({
  id: '/kalite-ve-guvenlik',
  path: '/kalite-ve-guvenlik',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const MesafeliSatisSozlesmesiRoute = MesafeliSatisSozlesmesiRouteImport.update({
  id: '/mesafeli-satis-sozlesmesi',
  path: '/mesafeli-satis-sozlesmesi',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeRoute = OdemeRouteImport.update({
  id: '/odeme',
  path: '/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const OnBilgilendirmeFormuRoute = OnBilgilendirmeFormuRouteImport.update({
  id: '/on-bilgilendirme-formu',
  path: '/on-bilgilendirme-formu',
  getParentRoute: () => rootRouteImport,
} as any)
const SepetRoute = SepetRouteImport.update({
  id: '/sepet',
  path: '/sepet',
  getParentRoute: () => rootRouteImport,
} as any)
const SikcaSorulanSorularRoute = SikcaSorulanSorularRouteImport.update({
  id: '/sikca-sorulan-sorular',
  path: '/sikca-sorulan-sorular',
  getParentRoute: () => rootRouteImport,
} as any)
const SiparisTakipRoute = SiparisTakipRouteImport.update({
  id: '/siparis-takip',
  path: '/siparis-takip',
  getParentRoute: () => rootRouteImport,
} as any)
const TeslimatPolitikasiRoute = TeslimatPolitikasiRouteImport.update({
  id: '/teslimat-politikasi',
  path: '/teslimat-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const TicariElektronikIletiOnayiRoute =
  TicariElektronikIletiOnayiRouteImport.update({
    id: '/ticari-elektronik-ileti-onayi',
    path: '/ticari-elektronik-ileti-onayi',
    getParentRoute: () => rootRouteImport,
  } as any)
const UyelikSozlesmesiRoute = UyelikSozlesmesiRouteImport.update({
  id: '/uyelik-sozlesmesi',
  path: '/uyelik-sozlesmesi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHesabimRoute = AuthenticatedHesabimRouteImport.update({
  id: '/hesabim',
  path: '/hesabim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedYonetimRoute = AuthenticatedYonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const UrunlerIndexRoute = UrunlerIndexRouteImport.update({
  id: '/urunler/',
  path: '/urunler/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerSlugRoute = UrunlerSlugRouteImport.update({
  id: '/urunler/$slug',
  path: '/urunler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSiparislerimIndexRoute =
  AuthenticatedSiparislerimIndexRouteImport.update({
    id: '/siparislerim/',
    path: '/siparislerim/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiparislerimOrderNumberRoute =
  AuthenticatedSiparislerimOrderNumberRouteImport.update({
    id: '/siparislerim/$orderNumber',
    path: '/siparislerim/$orderNumber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arama': typeof AramaRoute
  '/bilgi-merkezi': typeof BilgiMerkeziRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/giris': typeof GirisRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iade-ve-iptal-politikasi': typeof IadeVeIptalPolitikasiRoute
  '/iletisim': typeof IletisimRoute
  '/kalite-ve-guvenlik': typeof KaliteVeGuvenlikRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/odeme': typeof OdemeRoute
  '/on-bilgilendirme-formu': typeof OnBilgilendirmeFormuRoute
  '/sepet': typeof SepetRoute
  '/sikca-sorulan-sorular': typeof SikcaSorulanSorularRoute
  '/siparis-takip': typeof SiparisTakipRoute
  '/teslimat-politikasi': typeof TeslimatPolitikasiRoute
  '/ticari-elektronik-ileti-onayi': typeof TicariElektronikIletiOnayiRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/hesabim': typeof AuthenticatedHesabimRoute
  '/yonetim': typeof AuthenticatedYonetimRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/urunler/': typeof UrunlerIndexRoute
  '/siparislerim/$orderNumber': typeof AuthenticatedSiparislerimOrderNumberRoute
  '/siparislerim/': typeof AuthenticatedSiparislerimIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arama': typeof AramaRoute
  '/bilgi-merkezi': typeof BilgiMerkeziRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/giris': typeof GirisRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iade-ve-iptal-politikasi': typeof IadeVeIptalPolitikasiRoute
  '/iletisim': typeof IletisimRoute
  '/kalite-ve-guvenlik': typeof KaliteVeGuvenlikRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/odeme': typeof OdemeRoute
  '/on-bilgilendirme-formu': typeof OnBilgilendirmeFormuRoute
  '/sepet': typeof SepetRoute
  '/sikca-sorulan-sorular': typeof SikcaSorulanSorularRoute
  '/siparis-takip': typeof SiparisTakipRoute
  '/teslimat-politikasi': typeof TeslimatPolitikasiRoute
  '/ticari-elektronik-ileti-onayi': typeof TicariElektronikIletiOnayiRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/hesabim': typeof AuthenticatedHesabimRoute
  '/yonetim': typeof AuthenticatedYonetimRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/urunler': typeof UrunlerIndexRoute
  '/siparislerim/$orderNumber': typeof AuthenticatedSiparislerimOrderNumberRoute
  '/siparislerim': typeof AuthenticatedSiparislerimIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/arama': typeof AramaRoute
  '/bilgi-merkezi': typeof BilgiMerkeziRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/giris': typeof GirisRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iade-ve-iptal-politikasi': typeof IadeVeIptalPolitikasiRoute
  '/iletisim': typeof IletisimRoute
  '/kalite-ve-guvenlik': typeof KaliteVeGuvenlikRoute
  '/kvkk': typeof KvkkRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/odeme': typeof OdemeRoute
  '/on-bilgilendirme-formu': typeof OnBilgilendirmeFormuRoute
  '/sepet': typeof SepetRoute
  '/sikca-sorulan-sorular': typeof SikcaSorulanSorularRoute
  '/siparis-takip': typeof SiparisTakipRoute
  '/teslimat-politikasi': typeof TeslimatPolitikasiRoute
  '/ticari-elektronik-ileti-onayi': typeof TicariElektronikIletiOnayiRoute
  '/uyelik-sozlesmesi': typeof UyelikSozlesmesiRoute
  '/_authenticated/hesabim': typeof AuthenticatedHesabimRoute
  '/_authenticated/yonetim': typeof AuthenticatedYonetimRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/urunler/': typeof UrunlerIndexRoute
  '/_authenticated/siparislerim/$orderNumber': typeof AuthenticatedSiparislerimOrderNumberRoute
  '/_authenticated/siparislerim/': typeof AuthenticatedSiparislerimIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arama'
    | '/bilgi-merkezi'
    | '/cerez-politikasi'
    | '/giris'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iade-ve-iptal-politikasi'
    | '/iletisim'
    | '/kalite-ve-guvenlik'
    | '/kvkk'
    | '/mesafeli-satis-sozlesmesi'
    | '/odeme'
    | '/on-bilgilendirme-formu'
    | '/sepet'
    | '/sikca-sorulan-sorular'
    | '/siparis-takip'
    | '/teslimat-politikasi'
    | '/ticari-elektronik-ileti-onayi'
    | '/uyelik-sozlesmesi'
    | '/hesabim'
    | '/yonetim'
    | '/urunler/$slug'
    | '/urunler/'
    | '/siparislerim/$orderNumber'
    | '/siparislerim/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arama'
    | '/bilgi-merkezi'
    | '/cerez-politikasi'
    | '/giris'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iade-ve-iptal-politikasi'
    | '/iletisim'
    | '/kalite-ve-guvenlik'
    | '/kvkk'
    | '/mesafeli-satis-sozlesmesi'
    | '/odeme'
    | '/on-bilgilendirme-formu'
    | '/sepet'
    | '/sikca-sorulan-sorular'
    | '/siparis-takip'
    | '/teslimat-politikasi'
    | '/ticari-elektronik-ileti-onayi'
    | '/uyelik-sozlesmesi'
    | '/hesabim'
    | '/yonetim'
    | '/urunler/$slug'
    | '/urunler'
    | '/siparislerim/$orderNumber'
    | '/siparislerim'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/arama'
    | '/bilgi-merkezi'
    | '/cerez-politikasi'
    | '/giris'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iade-ve-iptal-politikasi'
    | '/iletisim'
    | '/kalite-ve-guvenlik'
    | '/kvkk'
    | '/mesafeli-satis-sozlesmesi'
    | '/odeme'
    | '/on-bilgilendirme-formu'
    | '/sepet'
    | '/sikca-sorulan-sorular'
    | '/siparis-takip'
    | '/teslimat-politikasi'
    | '/ticari-elektronik-ileti-onayi'
    | '/uyelik-sozlesmesi'
    | '/_authenticated/hesabim'
    | '/_authenticated/yonetim'
    | '/urunler/$slug'
    | '/urunler/'
    | '/_authenticated/siparislerim/$orderNumber'
    | '/_authenticated/siparislerim/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AramaRoute: typeof AramaRoute
  BilgiMerkeziRoute: typeof BilgiMerkeziRoute
  CerezPolitikasiRoute: typeof CerezPolitikasiRoute
  GirisRoute: typeof GirisRoute
  GizlilikPolitikasiRoute: typeof GizlilikPolitikasiRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IadeVeIptalPolitikasiRoute: typeof IadeVeIptalPolitikasiRoute
  IletisimRoute: typeof IletisimRoute
  KaliteVeGuvenlikRoute: typeof KaliteVeGuvenlikRoute
  KvkkRoute: typeof KvkkRoute
  MesafeliSatisSozlesmesiRoute: typeof MesafeliSatisSozlesmesiRoute
  OdemeRoute: typeof OdemeRoute
  OnBilgilendirmeFormuRoute: typeof OnBilgilendirmeFormuRoute
  SepetRoute: typeof SepetRoute
  SikcaSorulanSorularRoute: typeof SikcaSorulanSorularRoute
  SiparisTakipRoute: typeof SiparisTakipRoute
  TeslimatPolitikasiRoute: typeof TeslimatPolitikasiRoute
  TicariElektronikIletiOnayiRoute: typeof TicariElektronikIletiOnayiRoute
  UyelikSozlesmesiRoute: typeof UyelikSozlesmesiRoute
  UrunlerSlugRoute: typeof UrunlerSlugRoute
  UrunlerIndexRoute: typeof UrunlerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arama': {
      id: '/arama'
      path: '/arama'
      fullPath: '/arama'
      preLoaderRoute: typeof AramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilgi-merkezi': {
      id: '/bilgi-merkezi'
      path: '/bilgi-merkezi'
      fullPath: '/bilgi-merkezi'
      preLoaderRoute: typeof BilgiMerkeziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerez-politikasi': {
      id: '/cerez-politikasi'
      path: '/cerez-politikasi'
      fullPath: '/cerez-politikasi'
      preLoaderRoute: typeof CerezPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik-politikasi': {
      id: '/gizlilik-politikasi'
      path: '/gizlilik-politikasi'
      fullPath: '/gizlilik-politikasi'
      preLoaderRoute: typeof GizlilikPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iade-ve-iptal-politikasi': {
      id: '/iade-ve-iptal-politikasi'
      path: '/iade-ve-iptal-politikasi'
      fullPath: '/iade-ve-iptal-politikasi'
      preLoaderRoute: typeof IadeVeIptalPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalite-ve-guvenlik': {
      id: '/kalite-ve-guvenlik'
      path: '/kalite-ve-guvenlik'
      fullPath: '/kalite-ve-guvenlik'
      preLoaderRoute: typeof KaliteVeGuvenlikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesafeli-satis-sozlesmesi': {
      id: '/mesafeli-satis-sozlesmesi'
      path: '/mesafeli-satis-sozlesmesi'
      fullPath: '/mesafeli-satis-sozlesmesi'
      preLoaderRoute: typeof MesafeliSatisSozlesmesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme': {
      id: '/odeme'
      path: '/odeme'
      fullPath: '/odeme'
      preLoaderRoute: typeof OdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-bilgilendirme-formu': {
      id: '/on-bilgilendirme-formu'
      path: '/on-bilgilendirme-formu'
      fullPath: '/on-bilgilendirme-formu'
      preLoaderRoute: typeof OnBilgilendirmeFormuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sepet': {
      id: '/sepet'
      path: '/sepet'
      fullPath: '/sepet'
      preLoaderRoute: typeof SepetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sikca-sorulan-sorular': {
      id: '/sikca-sorulan-sorular'
      path: '/sikca-sorulan-sorular'
      fullPath: '/sikca-sorulan-sorular'
      preLoaderRoute: typeof SikcaSorulanSorularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siparis-takip': {
      id: '/siparis-takip'
      path: '/siparis-takip'
      fullPath: '/siparis-takip'
      preLoaderRoute: typeof SiparisTakipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teslimat-politikasi': {
      id: '/teslimat-politikasi'
      path: '/teslimat-politikasi'
      fullPath: '/teslimat-politikasi'
      preLoaderRoute: typeof TeslimatPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticari-elektronik-ileti-onayi': {
      id: '/ticari-elektronik-ileti-onayi'
      path: '/ticari-elektronik-ileti-onayi'
      fullPath: '/ticari-elektronik-ileti-onayi'
      preLoaderRoute: typeof TicariElektronikIletiOnayiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uyelik-sozlesmesi': {
      id: '/uyelik-sozlesmesi'
      path: '/uyelik-sozlesmesi'
      fullPath: '/uyelik-sozlesmesi'
      preLoaderRoute: typeof UyelikSozlesmesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hesabim': {
      id: '/_authenticated/hesabim'
      path: '/hesabim'
      fullPath: '/hesabim'
      preLoaderRoute: typeof AuthenticatedHesabimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yonetim': {
      id: '/_authenticated/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof AuthenticatedYonetimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/urunler/': {
      id: '/urunler/'
      path: '/urunler'
      fullPath: '/urunler/'
      preLoaderRoute: typeof UrunlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/$slug': {
      id: '/urunler/$slug'
      path: '/urunler/$slug'
      fullPath: '/urunler/$slug'
      preLoaderRoute: typeof UrunlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/siparislerim/': {
      id: '/_authenticated/siparislerim/'
      path: '/siparislerim'
      fullPath: '/siparislerim/'
      preLoaderRoute: typeof AuthenticatedSiparislerimIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/siparislerim/$orderNumber': {
      id: '/_authenticated/siparislerim/$orderNumber'
      path: '/siparislerim/$orderNumber'
      fullPath: '/siparislerim/$orderNumber'
      preLoaderRoute: typeof AuthenticatedSiparislerimOrderNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHesabimRoute: typeof AuthenticatedHesabimRoute
  AuthenticatedYonetimRoute: typeof AuthenticatedYonetimRoute
  AuthenticatedSiparislerimOrderNumberRoute: typeof AuthenticatedSiparislerimOrderNumberRoute
  AuthenticatedSiparislerimIndexRoute: typeof AuthenticatedSiparislerimIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHesabimRoute: AuthenticatedHesabimRoute,
  AuthenticatedYonetimRoute: AuthenticatedYonetimRoute,
  AuthenticatedSiparislerimOrderNumberRoute:
    AuthenticatedSiparislerimOrderNumberRoute,
  AuthenticatedSiparislerimIndexRoute: AuthenticatedSiparislerimIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AramaRoute: AramaRoute,
  BilgiMerkeziRoute: BilgiMerkeziRoute,
  CerezPolitikasiRoute: CerezPolitikasiRoute,
  GirisRoute: GirisRoute,
  GizlilikPolitikasiRoute: GizlilikPolitikasiRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IadeVeIptalPolitikasiRoute: IadeVeIptalPolitikasiRoute,
  IletisimRoute: IletisimRoute,
  KaliteVeGuvenlikRoute: KaliteVeGuvenlikRoute,
  KvkkRoute: KvkkRoute,
  MesafeliSatisSozlesmesiRoute: MesafeliSatisSozlesmesiRoute,
  OdemeRoute: OdemeRoute,
  OnBilgilendirmeFormuRoute: OnBilgilendirmeFormuRoute,
  SepetRoute: SepetRoute,
  SikcaSorulanSorularRoute: SikcaSorulanSorularRoute,
  SiparisTakipRoute: SiparisTakipRoute,
  TeslimatPolitikasiRoute: TeslimatPolitikasiRoute,
  TicariElektronikIletiOnayiRoute: TicariElektronikIletiOnayiRoute,
  UyelikSozlesmesiRoute: UyelikSozlesmesiRoute,
  UrunlerSlugRoute: UrunlerSlugRoute,
  UrunlerIndexRoute: UrunlerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
