CREATE TABLE public.operational_incidents (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),market_id uuid REFERENCES public.markets(id) ON DELETE RESTRICT,
 title text NOT NULL CHECK(char_length(title) BETWEEN 3 AND 160),severity text NOT NULL CHECK(severity IN('low','medium','high','critical')),
 status text NOT NULL DEFAULT 'open' CHECK(status IN('open','investigating','monitoring','resolved')),
 source text NOT NULL DEFAULT 'manual',description text NOT NULL DEFAULT '',assigned_to uuid REFERENCES auth.users(id) ON DELETE SET NULL,
 opened_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,resolved_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK(status<>'resolved' OR resolved_at IS NOT NULL)
);
CREATE TABLE public.incident_updates(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,incident_id uuid NOT NULL REFERENCES public.operational_incidents(id) ON DELETE RESTRICT,author_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,status text NOT NULL,note text NOT NULL CHECK(char_length(note) BETWEEN 2 AND 2000),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX operational_incidents_queue_idx ON public.operational_incidents(status,severity,created_at DESC);ALTER TABLE public.operational_incidents ENABLE ROW LEVEL SECURITY;ALTER TABLE public.incident_updates ENABLE ROW LEVEL SECURITY;GRANT ALL ON public.operational_incidents,public.incident_updates TO service_role;CREATE TRIGGER operational_incidents_set_updated_at BEFORE UPDATE ON public.operational_incidents FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE OR REPLACE FUNCTION public.admin_list_incidents(p_actor_id uuid,p_market_code text DEFAULT 'TR')RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$DECLARE m uuid;BEGIN IF NOT public.has_permission(p_actor_id,'operations.read')THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='FORBIDDEN';END IF;SELECT id INTO m FROM public.markets WHERE code=upper(p_market_code);RETURN(SELECT coalesce(jsonb_agg(jsonb_build_object('id',i.id,'title',i.title,'severity',i.severity,'status',i.status,'source',i.source,'description',i.description,'assignedTo',i.assigned_to,'createdAt',i.created_at,'updatedAt',i.updated_at,'updates',(SELECT coalesce(jsonb_agg(jsonb_build_object('status',u.status,'note',u.note,'createdAt',u.created_at)ORDER BY u.created_at DESC),'[]'::jsonb)FROM public.incident_updates u WHERE u.incident_id=i.id))ORDER BY CASE i.severity WHEN'critical'THEN 1 WHEN'high'THEN 2 WHEN'medium'THEN 3 ELSE 4 END,i.created_at DESC),'[]'::jsonb)FROM public.operational_incidents i WHERE i.market_id=m);END$$;
CREATE OR REPLACE FUNCTION public.admin_save_incident(p_actor_id uuid,p_incident_id uuid,p_market_code text,p_title text,p_severity text,p_status text,p_description text,p_note text DEFAULT NULL)RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$DECLARE m uuid;i uuid;BEGIN IF NOT public.has_permission(p_actor_id,'operations.read')THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='FORBIDDEN';END IF;SELECT id INTO m FROM public.markets WHERE code=upper(p_market_code);IF p_incident_id IS NULL THEN INSERT INTO public.operational_incidents(market_id,title,severity,status,description,opened_by,resolved_at)VALUES(m,trim(p_title),p_severity,p_status,p_description,p_actor_id,CASE WHEN p_status='resolved'THEN now()END)RETURNING id INTO i;ELSE UPDATE public.operational_incidents SET title=trim(p_title),severity=p_severity,status=p_status,description=p_description,resolved_at=CASE WHEN p_status='resolved'THEN coalesce(resolved_at,now())ELSE NULL END WHERE id=p_incident_id AND market_id=m RETURNING id INTO i;END IF;IF nullif(trim(p_note),'')IS NOT NULL THEN INSERT INTO public.incident_updates(incident_id,author_id,status,note)VALUES(i,p_actor_id,p_status,trim(p_note));END IF;INSERT INTO public.audit_events(market_id,actor_id,actor_type,action,resource_type,resource_id,metadata)VALUES(m,p_actor_id,'admin','incident.saved','incident',i::text,jsonb_build_object('severity',p_severity,'status',p_status));RETURN i;END$$;
REVOKE ALL ON FUNCTION public.admin_list_incidents(uuid,text),public.admin_save_incident(uuid,uuid,text,text,text,text,text,text)FROM PUBLIC,anon,authenticated;GRANT EXECUTE ON FUNCTION public.admin_list_incidents(uuid,text),public.admin_save_incident(uuid,uuid,text,text,text,text,text,text)TO service_role;
